###============================================================================
### GLOBAL/DEFAULT PROPERTIES
###============================================================================

server:
    port: 8080

maxSession: 5

###============================================================================
### DEVELOPMENT PROPERTIES
###============================================================================

---

server:
    port: 8080

maxSession: 5
